version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8081:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:tai03102004@db:5432/sonic
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tai03102004
      - POSTGRES_DB=sonic
    ports:
      - "5433:5432"
